package lila.puzzle

import play.api.libs.json.*

import PuzzleFixtures.*

// The browser's puzzle is goban's puzzle format (`Puzzle` in libs/board/src/puzzle.ts) plus lila's fields.
class JsonViewTest extends munit.FunSuite:

  private def puzzleOf(p: JsObject): Puzzle = BsonHandlers.puzzleReader.readDocument(mongoDoc(p)).get

  // the fields of `Puzzle` in libs/board/src/puzzle.ts, and the ones tools/puzzles/data's files have
  private val gobanFields = List(
    "width",
    "height",
    "bounds",
    "initial_state",
    "initial_player",
    "move_tree",
    "puzzle_player_move_mode",
    "puzzle_opponent_move_mode"
  )

  test("every field of goban's puzzle is there, as the generator wrote it"):
    generated.foreach: p =>
      val json = JsonView.puzzleJson(puzzleOf(p))
      gobanFields.foreach: field =>
        assertEquals(json \ field, JsDefined((p \ field).get), s"${(p \ "id").as[String]} $field")

  test("lila's fields: id, rating, plays, themes, goal and the source line"):
    generated.foreach: p =>
      val json = JsonView.puzzleJson(puzzleOf(p))
      assertEquals((json \ "id").as[String], (p \ "id").as[String])
      assertEquals((json \ "rating").as[Int], (p \ "rating").as[Int])
      assertEquals((json \ "plays").as[Int], 0)
      assertEquals((json \ "themes").as[Set[String]], (p \ "themes").as[Set[String]])
      assertEquals((json \ "goal").as[String], (p \ "goal").as[String])
      assertEquals((json \ "source").as[String], "Generated by LiGo (seed 1)")

  test("a puzzle without bounds has no bounds field, so goban shows the whole board"):
    val noBounds = puzzleOf(generated.head).copy(bounds = None)
    assert((JsonView.puzzleJson(noBounds) \ "bounds").isEmpty)

  test("the activity stream's puzzle has no board and no tree"):
    val json = JsonView.puzzleJsonStandalone(puzzleOf(generated.head))
    assert((json \ "move_tree").isEmpty)
    assert((json \ "initial_state").isEmpty)
    assertEquals((json \ "goal").as[String], "kill")

  test("/api/puzzle/many lists puzzles under \"puzzle\""):
    val json = (JsonView().many(generated.map(puzzleOf)) \ "puzzles").as[List[JsObject]]
    assertEquals(json.map(j => (j \ "puzzle" \ "id").as[String]), generated.map(p => (p \ "id").as[String]))

  test("the mini board draws the setup stones inside the bounds, and nothing else"):
    val puzzle = puzzleOf(generated.head)
    val svg = PuzzleMiniBoard.svg(puzzle)
    val b = puzzle.bounds.get
    def inside(points: String) =
      Puzzle.sgfPoints(points).count((c, r) => c >= b.left && c <= b.right && r >= b.top && r <= b.bottom)
    val stones = "<circle ".r.findAllIn(svg).size
    assertEquals(stones, inside(puzzle.setup.black) + inside(puzzle.setup.white))
    assert(svg.startsWith("<svg ") && svg.endsWith("</svg>"))
    assertEquals("<path ".r.findAllIn(svg).size, (b.right - b.left + 1) + (b.bottom - b.top + 1))
