package lila.puzzle

import chess.IntRating
import play.api.libs.json.*
import reactivemongo.api.bson.*

import PuzzleFixtures.*

// ADR 0025 section 5: the server reads the document the loader writes.
class PuzzleBsonTest extends munit.FunSuite:

  private def read(doc: BSONDocument): Puzzle =
    BsonHandlers.puzzleReader.readDocument(doc).get

  test("reads the document the loader writes"):
    generated.foreach: p =>
      val puzzle = read(mongoDoc(p))
      assertEquals(puzzle.id.value, (p \ "id").as[String])
      assertEquals(puzzle.size, (p \ "width").as[Int])
      assertEquals(puzzle.color.name, (p \ "initial_player").as[String])
      assertEquals(puzzle.goal, (p \ "goal").as[String])
      assertEquals(puzzle.setup.black, (p \ "initial_state" \ "black").as[String])
      assertEquals(puzzle.setup.white, (p \ "initial_state" \ "white").as[String])
      assertEquals(puzzle.themes.map(_.value), (p \ "themes").as[Set[String]])
      assertEquals(puzzle.glicko.intRating, IntRating((p \ "rating").as[Int]))
      assertEquals(puzzle.glicko.deviation, 500d)
      assertEquals(puzzle.plays, 0)
      assertEquals(puzzle.vote, 0f)
      val b = (p \ "bounds").as[JsObject]
      assertEquals(
        puzzle.bounds,
        Some(
          Puzzle.Bounds(
            (b \ "top").as[Int],
            (b \ "left").as[Int],
            (b \ "bottom").as[Int],
            (b \ "right").as[Int]
          )
        )
      )

  test("keeps the tree as it is stored"):
    generated.foreach: p =>
      val doc = mongoDoc(p)
      val puzzle = read(doc)
      assertEquals(Some(puzzle.tree), doc.get("tree").collect { case d: BSONDocument => d })
      assertEquals(lila.db.JSON.jval(puzzle.tree), (p \ "move_tree").as[JsObject])

  test("accepts numbers written as doubles, as the JSON helper and older shells write them"):
    val p = generated.head
    val bounds = BSONDocument(
      "top" -> BSONDouble(1),
      "left" -> BSONLong(2),
      "bottom" -> BSONInteger(3),
      "right" -> BSONDouble(4)
    )
    val asDoubles = updated(
      mongoDoc(p),
      BSONDocument(
        "size" -> BSONDouble(19),
        "plays" -> BSONDouble(3),
        "vote" -> BSONInteger(0),
        "bounds" -> bounds
      )
    )
    val puzzle = read(asDoubles)
    assertEquals(puzzle.size, 19)
    assertEquals(puzzle.plays, 3)
    assertEquals(puzzle.bounds, Some(Puzzle.Bounds(1, 2, 3, 4)))

  test("bounds are optional"):
    assertEquals(read(without(mongoDoc(generated.head), "bounds")).bounds, None)

  test("provenance is optional on read and kept when there"):
    val p = generated.head
    assert(read(mongoDoc(p)).prov.isDefined)
    assertEquals(read(without(mongoDoc(p), "prov")).prov, None)

  test("a document without a tree, a player or a goal is refused"):
    val doc = mongoDoc(generated.head)
    List("tree", "player", "goal").foreach: key =>
      assert(BsonHandlers.puzzleReader.readDocument(without(doc, key)).isFailure, s"without $key")
    assert(BsonHandlers.puzzleReader.readDocument(updated(doc, BSONDocument("player" -> "green"))).isFailure)

  test("the source line"):
    val generatedProv = read(mongoDoc(generated.head)).source
    assertEquals(generatedProv, "Generated by LiGo (seed 1)")
    val classic = BSONDocument(
      "source" -> "transcribed",
      "work" -> "Gokyō Shumyō",
      "edition" -> "1812",
      "problem" -> "12"
    )
    assertEquals(Puzzle.sourceLine(Some(classic)), "Gokyō Shumyō (1812), problem 12")
    assertEquals(Puzzle.sourceLine(Some(BSONDocument("source" -> "generated"))), "Generated by LiGo")
    assertEquals(Puzzle.sourceLine(None), "Source unknown")

  test("SGF point lists"):
    assertEquals(Puzzle.sgfPoints("aabbss"), List((0, 0), (1, 1), (18, 18)))
    assertEquals(Puzzle.sgfPoints(""), Nil)
    assertEquals(Puzzle.sgfPoints("aab"), List((0, 0)))
