// Puzzles as SGF, both ways (ADR 0025 §1, PLAN unit 8.3):
//   - `toSgf` writes a puzzle so it opens in Sabaki or any SGF editor: setup stones, `PL`, the
//     tree, "RIGHT" and "WRONG" in the comments (goproblems' convention). The JSON stays the truth.
//   - `fromSgf` reads a hand-transcribed problem (the classics tail, ADR 0024 §2) in the same
//     convention into a puzzle, through libs/board's SGF reader (unit 7.2), which replays every
//     move with LiGo's rules. The caller gives the provenance, bounds, goal, themes and rating;
//     the result still has to pass `check`.
//
// Licence: MIT (LiGo's own code, ADR 0007).
// libs/board is imported by path, not as a workspace package (see src/katago.ts).
import { readTree, type GoNode } from '../../../libs/board/src/sgf.mjs';
import { fromSgf as pointOf, sgfPoint } from './goban.ts';
import type { Bounds, Goal, Puzzle, Theme, Transcribed } from './puzzle.ts';
import type { MoveTreeJson } from './tree.ts';

const GOAL_TEXT: Record<Goal, string> = {
  live: 'to live',
  kill: 'to kill',
  ko: 'to make ko',
  capture: 'to win the capturing race',
  connect: 'to connect',
};

const escape = (s: string) => s.replace(/\\/g, '\\\\').replace(/]/g, '\\]');

export function toSgf(p: Puzzle): string {
  const first = p.initial_player === 'black' ? 'B' : 'W';
  const other = (c: string) => (c === 'B' ? 'W' : 'B');
  const node = (n: MoveTreeJson, colour: string): string => {
    const notes = [n.text, n.correct_answer ? 'RIGHT' : n.wrong_answer ? 'WRONG' : undefined].filter(Boolean);
    const comment = notes.length ? `C[${escape(notes.join('\n'))}]` : '';
    return `;${colour}[${sgfPoint(n)}]${comment}${children(n.branches ?? [], other(colour))}`;
  };
  const children = (kids: MoveTreeJson[], colour: string): string =>
    kids.length === 1 ? node(kids[0], colour) : kids.map(k => `(${node(k, colour)})`).join('');
  const setup = (points: string) => (points.match(/../g) ?? []).map(q => `[${q}]`).join('');
  const who = p.initial_player === 'black' ? 'Black' : 'White';
  const source =
    p.provenance.source === 'generated'
      ? `Generated by LiGo (seed ${p.provenance.seed})`
      : `${p.provenance.work}, problem ${p.provenance.problem}`;
  const ab = p.initial_state.black ? `AB${setup(p.initial_state.black)}` : '';
  const aw = p.initial_state.white ? `AW${setup(p.initial_state.white)}` : '';
  return (
    `(;GM[1]FF[4]CA[UTF-8]AP[LiGo puzzles]SZ[${p.width}]PL[${first}]${ab}${aw}` +
    `GN[${p.id}]C[${escape(`${who} ${GOAL_TEXT[p.goal]}. ${source}. Licence: MIT.`)}]` +
    `${children(p.move_tree.branches ?? [], first)})\n`
  );
}

export interface Transcription {
  id: string;
  bounds: Bounds;
  goal: Goal;
  themes: Theme[];
  rating: number;
  provenance: Transcribed;
}

/**
 * A hand-transcribed problem: the SGF's setup and player to move, and its tree, where a line whose
 * last comment says "RIGHT" is right and any other line is wrong. Passes are refused (a puzzle's
 * tree has none). Throws libs/board's `SgfError` for an unreadable record.
 */
export function fromSgf(text: string, meta: Transcription): Puzzle {
  const root = readTree(text);
  const size = root.settings.size;
  const convert = (n: GoNode): MoveTreeJson => {
    if (!n.move || n.move === '..') throw new Error(`a pass or a node without a move at ply ${n.ply}`);
    const out: MoveTreeJson = { ...pointOf(n.move) };
    const note = n.comments
      .map(c => c.text)
      .join('\n')
      .trim();
    const right = /\bRIGHT\b/.test(note);
    const text = note.replace(/\b(RIGHT|WRONG)\b/g, '').trim();
    if (text) out.text = text;
    if (n.children.length) out.branches = n.children.map(convert);
    else if (right) out.correct_answer = true;
    else out.wrong_answer = true;
    return out;
  };
  return {
    id: meta.id,
    width: size,
    height: size,
    bounds: meta.bounds,
    initial_state: { black: root.settings.black.join(''), white: root.settings.white.join('') },
    initial_player: root.settings.toMove,
    move_tree: { x: -1, y: -1, branches: root.children.map(convert) },
    puzzle_player_move_mode: 'free',
    puzzle_opponent_move_mode: 'automatic',
    goal: meta.goal,
    themes: meta.themes,
    rating: meta.rating,
    provenance: meta.provenance,
  };
}
