// The Phase 8 demo (unit 8.8), at phone size: a signed-in player solves one puzzle and fails the next,
// tapping and confirming as on a phone, and watches the rating move both ways; then every puzzle of
// the committed set (tools/puzzles/data) opens on the trainer page with its stones, its goal and its
// source line. Like the other tests here it runs on the built page with a stand-in server (page.ts),
// so the rating change is the stand-in's; the same walk against the real server waits for unit 3.20's
// full-stack browser tests. docs/demos/phase-8.md is the owner's checklist on the real site.
import { expect, test, type Page } from '@playwright/test';

import { feedback, line, openPuzzle, play, position } from './page';
import { allPuzzles, centreThree, rightFirst, straightThree, wrongFirst, type PuzzleJson } from './puzzles';

const phone = { viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true };
test.use(phone);

const confirmButton = (page: Page) => page.getByRole('button', { name: 'Confirm move' });
const ratingShown = (page: Page) => page.locator('.puzzle__side__user__rating');

/** Taps a point, then Confirm move (touch screens confirm by default). */
async function tapAndConfirm(page: Page, move: string): Promise<void> {
  await play(page, move, true);
  await expect(confirmButton(page)).toBeEnabled();
  await confirmButton(page).click();
}

test('solve one puzzle, fail the next, and the rating moves both ways', async ({ page }) => {
  const opened = await openPuzzle(page, { puzzle: straightThree, next: centreThree, rating: 1500 });
  await expect(ratingShown(page).locator('strong')).toHaveText('1500');

  // solved: the rating goes up
  await tapAndConfirm(page, rightFirst(straightThree));
  await expect(feedback(page).locator('.complete')).toHaveText('Success!');
  await expect(ratingShown(page).locator('good.rp')).toHaveText('+8');

  // the next puzzle starts from the new rating
  await page.locator('.puzzle__feedback .continue').click();
  await expect(feedback(page)).toHaveClass(/play/);
  await expect(ratingShown(page).locator('strong')).toContainText('1508');
  await expect(page.locator('.puzzle__source')).toHaveText(centreThree.source);

  // failed: the refutation is on the board and the rating goes down
  const wrong = wrongFirst(centreThree);
  await tapAndConfirm(page, wrong);
  await expect(feedback(page)).toHaveClass(/fail/);
  expect((await line(page))[0]).toBe(wrong);
  await expect(ratingShown(page).locator('strong')).toContainText('1508');
  await expect(ratingShown(page).locator('bad.rp')).toHaveText('−8');

  // one result per puzzle, both rated; the session strip shows a win and a loss
  expect(opened.completed).toEqual([
    { theme: 'mix', id: straightThree.id, win: true, rated: true },
    { theme: 'mix', id: centreThree.id, win: false, rated: true },
  ]);
  await expect(page.locator('.puzzle__session a.result-true')).toHaveCount(1);
  await expect(page.locator('.puzzle__session a.result-false')).toHaveCount(1);
  expect(opened.problems).toEqual({ requests: [], errors: [] });
});

/** Stones of one colour on the board shown. */
const count = (rows: string[], stone: string) => rows.join('').split(stone).length - 1;

/** Black's or White's goal, as the page words it (src/go.ts). */
const goalWords = (p: PuzzleJson) =>
  `${p.initial_player === 'black' ? 'Black' : 'White'} to ${p.goal === 'kill' ? 'kill' : 'live'}`;

const puzzles = allPuzzles();
const chunk = 30;

test('the committed set has at least 200 puzzles, each with a source', () => {
  expect(puzzles.length).toBeGreaterThanOrEqual(200);
  for (const p of puzzles) expect(p.source, p.id).toMatch(/^Generated by LiGo \(seed \d+\)$/);
});

for (let from = 0; from < puzzles.length; from += chunk) {
  const some = puzzles.slice(from, from + chunk);
  test(`puzzles ${from + 1}–${from + some.length} open with their stones, goal and source`, async ({
    context,
  }) => {
    test.setTimeout(120_000);
    for (const p of some) {
      const page = await context.newPage();
      const opened = await openPuzzle(page, { puzzle: p, rating: 1500 });
      await expect(feedback(page), p.id).toContainText(goalWords(p));
      await expect(page.locator('.puzzle__source'), p.id).toHaveText(p.source);
      const rows = await position(page);
      expect(count(rows, 'X'), `${p.id} black stones`).toBe(p.initial_state.black.length / 2);
      expect(count(rows, 'O'), `${p.id} white stones`).toBe(p.initial_state.white.length / 2);
      // the board fits the phone's width
      const box = (await page.locator('.puzzle__go-board svg').first().boundingBox())!;
      expect(box.x + box.width, p.id).toBeLessThanOrEqual(phone.viewport.width);
      expect(opened.problems, p.id).toEqual({ requests: [], errors: [] });
      await page.close();
    }
  });
}
