// The puzzles the browser tests play: real ones from the committed set (tools/puzzles/data, as
// `JsonView.puzzleJson` sends them: goban's puzzle format plus lila's `id`, `rating`, `plays`,
// `themes`, `goal` and `source`), and the straight three in the corner that libs/board's tests use.

import { readFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

export interface Tree {
  x: number;
  y: number;
  branches?: Tree[];
  correct_answer?: boolean;
  wrong_answer?: boolean;
}

export interface PuzzleJson {
  id: string;
  rating: number;
  plays: number;
  themes: string[];
  goal: string;
  source: string;
  width: number;
  height: number;
  bounds: { top: number; left: number; bottom: number; right: number };
  initial_state: { black: string; white: string };
  initial_player: 'black' | 'white';
  move_tree: Tree;
  puzzle_player_move_mode: 'free';
  puzzle_opponent_move_mode: 'automatic';
}

const dataDir = join(dirname(fileURLToPath(import.meta.url)), '../../../../tools/puzzles/data');

/** A puzzle of the committed set as lila's JSON has it (`JsonView.puzzleJson`, `Puzzle.sourceLine`). */
const asLila = (found: any): PuzzleJson => ({
  id: found.id,
  rating: found.rating,
  plays: 0,
  themes: found.themes,
  goal: found.goal,
  source: `Generated by LiGo (seed ${found.provenance.seed})`,
  width: found.width,
  height: found.height,
  bounds: found.bounds,
  initial_state: found.initial_state,
  initial_player: found.initial_player,
  move_tree: found.move_tree,
  puzzle_player_move_mode: 'free',
  puzzle_opponent_move_mode: 'automatic',
});

/** Every puzzle of the committed set, in file order. */
export const allPuzzles = (): PuzzleJson[] =>
  readdirSync(dataDir)
    .filter(f => /^generated-.*\.json$/.test(f))
    .sort()
    .flatMap(file => JSON.parse(readFileSync(join(dataDir, file), 'utf8')).map(asLila));

/** A puzzle of the committed set. */
function fromSet(id: string): PuzzleJson {
  const found = allPuzzles().find(p => p.id === id);
  if (!found) throw new Error(`puzzle ${id} is not in ${dataDir}`);
  return found;
}

/** The straight three in the corner, Black to live: b1 is right; a1 and c1 are refuted by White at b1. */
export const straightThree: PuzzleJson = {
  id: 'strt3',
  rating: 700,
  plays: 12,
  themes: ['lifeAndDeath', 'living', 'corner', 'eyeShape'],
  goal: 'live',
  source: 'Generated by LiGo (seed 1)',
  width: 19,
  height: 19,
  bounds: { top: 0, left: 0, bottom: 4, right: 6 },
  initial_state: { black: 'abbbcbdbda', white: 'acbcccdcecebea' },
  initial_player: 'black',
  move_tree: {
    x: -1,
    y: -1,
    branches: [
      { x: 1, y: 0, correct_answer: true },
      { x: 0, y: 0, branches: [{ x: 1, y: 0, wrong_answer: true }] },
      { x: 2, y: 0, branches: [{ x: 1, y: 0, wrong_answer: true }] },
    ],
  },
  puzzle_player_move_mode: 'free',
  puzzle_opponent_move_mode: 'automatic',
};

/** A corner puzzle whose right line is three moves long: White kills the pyramid four. */
export const pyramidFour: PuzzleJson = fromSet('GUZrD');

/** A puzzle in the middle of the board, to come next. */
export const centreThree: PuzzleJson = fromSet('18Q2Y');

/** The first point of the first right line: a move that is right, to play. */
export function rightFirst(puzzle: PuzzleJson): string {
  const n = puzzle.move_tree.branches!.find(
    b => !b.wrong_answer && (b.correct_answer || b.branches?.length),
  )!;
  return String.fromCharCode(97 + n.x, 97 + n.y);
}

/** A first move that is wrong: one whose reply is marked wrong. */
export function wrongFirst(puzzle: PuzzleJson): string {
  const n = puzzle.move_tree.branches!.find(b => b.branches?.some(r => r.wrong_answer))!;
  return String.fromCharCode(97 + n.x, 97 + n.y);
}
