// The trainer page on the built page (unit 8.7): solving a puzzle, a wrong line with its refutation
// and a retry, "view the solution", the rating change and the next puzzle, touch-confirm, and the
// themes. goban decides right and wrong (libs/board's puzzle board, unit 8.5); these tests check what
// the page does with its answers: the words, the board, and what it sends to the server. The server is
// a stand-in (page.ts).
import { expect, test, type Page } from '@playwright/test';

import { ConfirmMoves, boardMoves, feedback, key, line, openPuzzle, play, position, sounds } from './page';
import { centreThree, pyramidFour, rightFirst, straightThree, wrongFirst } from './puzzles';

/** The stone at an SGF point of the position shown: `.`, `X` (black) or `O` (white). */
async function stoneAt(page: Page, move: string): Promise<string> {
  const rows = await position(page);
  return rows[move.charCodeAt(1) - 97][move.charCodeAt(0) - 97];
}

const viewSolutionButton = (page: Page) => page.locator('.puzzle__feedback .puzzle__view-solution');

test.describe('desktop', () => {
  test.use({ viewport: { width: 1280, height: 800 } });

  test('a signed-in player solves the straight three, and the next puzzle comes', async ({ page }) => {
    const opened = await openPuzzle(page, { puzzle: straightThree, next: centreThree, rating: 1500 });

    await expect(feedback(page)).toHaveClass(/play/);
    await expect(feedback(page).locator('strong')).toHaveText('Your turn');
    await expect(feedback(page)).toContainText('Find the best move for black.');
    await expect(feedback(page)).toContainText('Black to live');
    // the source line, under the board
    await expect(page.locator('.puzzle__source')).toHaveText('Generated by LiGo (seed 1)');
    // lila hides the puzzle's rating until it is over
    await expect(page.locator('.puzzle__side__metas')).toContainText('Rating: hidden');
    await expect(page.locator('.puzzle__side__user__rating strong')).toHaveText('1500');
    await expect(page.locator('.puzzle__side__theme')).toContainText('Puzzle themes');

    await play(page, rightFirst(straightThree));
    await expect(feedback(page)).toHaveClass(/after/);
    await expect(feedback(page).locator('.complete')).toHaveText('Success!');
    expect(opened.completed).toEqual([{ theme: 'mix', id: 'strt3', win: true, rated: true }]);
    // the rating change from the server's answer, and the puzzle's own rating, now shown
    await expect(page.locator('.puzzle__side__user__rating strong')).toContainText('1500');
    await expect(page.locator('.puzzle__side__user__rating good.rp')).toHaveText('+8');
    await expect(page.locator('.puzzle__side__metas')).toContainText('Rating: 700');
    await expect(page.locator('.puzzle__session a.result-true')).toHaveCount(1);
    await expect(page.locator('.puzzle__themes__list__entry a')).toHaveText([
      'Corner',
      'Eye shape',
      'Life and death',
      'Living',
    ]);

    // the next puzzle, by lila's xhr flow
    await page.locator('.puzzle__feedback .continue').click();
    await expect(page.locator('.puzzle__side__metas a')).toHaveText('#18Q2Y');
    await expect(feedback(page)).toHaveClass(/play/);
    await expect(feedback(page)).toContainText('Black to live');
    await expect(page.locator('.puzzle__source')).toHaveText('Generated by LiGo (seed 1)');
    await expect(page.locator('.puzzle__side__user__rating strong')).toContainText('1508');
    await expect(page).toHaveURL(/\/training\/mix$/);
    expect(await line(page)).toEqual([]);
    expect(opened.completed).toHaveLength(1);
    expect(opened.problems).toEqual({ requests: [], errors: [] });
  });

  test('a wrong move shows the refutation, and Try again starts over', async ({ page }) => {
    const opened = await openPuzzle(page, { puzzle: straightThree, next: centreThree, rating: 1500 });
    const wrong = wrongFirst(straightThree);
    const right = rightFirst(straightThree);
    const start = await position(page);

    await play(page, wrong);
    await expect(feedback(page)).toHaveClass(/fail/);
    await expect(feedback(page).locator('strong')).toHaveText("That's not the move!");
    // goban played White's refutation at b1 on the board, and the board takes no more moves
    expect(await line(page)).toEqual([wrong, right]);
    expect(await stoneAt(page, wrong)).toBe('X');
    expect(await stoneAt(page, right)).toBe('O');
    // the loss is sent at once, once, and the rating drops
    expect(opened.completed).toEqual([{ theme: 'mix', id: 'strt3', win: false, rated: true }]);
    await expect(page.locator('.puzzle__side__user__rating bad.rp')).toHaveText('−8');
    await play(page, 'cb');
    expect(await line(page)).toEqual([wrong, right]);

    await feedback(page).getByRole('button', { name: 'Try again' }).click();
    await expect(feedback(page)).toHaveClass(/play/);
    expect(await line(page)).toEqual([]);
    expect(await position(page)).toEqual(start);

    // the right move now: solved, but the result is not sent again
    await play(page, right);
    await expect(feedback(page)).toHaveClass(/after/);
    // solved on a second try: complete, not "Success!", and nothing is sent again
    await expect(feedback(page).locator('.complete')).toHaveText('Puzzle complete!');
    expect(opened.completed).toHaveLength(1);
    expect(opened.problems).toEqual({ requests: [], errors: [] });
  });

  test('"View the solution" steps through the right line in the move list', async ({ page }) => {
    const opened = await openPuzzle(page, { puzzle: pyramidFour, rating: 1500 });

    // lila shows the button a few seconds in
    await expect(feedback(page).locator('.view_solution')).toHaveClass(/show/, { timeout: 8000 });
    await viewSolutionButton(page).click();
    expect(opened.completed).toEqual([{ theme: 'mix', id: 'GUZrD', win: false, rated: true }]);
    await expect(feedback(page)).toHaveClass(/after/);

    const moves = page.locator('.puzzle__moves move');
    await expect(moves).toHaveCount(3);
    await expect(moves.first().locator('index')).toHaveText('1');
    const names = await moves.locator('san').allTextContents();
    expect(names).toHaveLength(3);
    // Black kills the pyramid: Black first, then White's answer, each named by its point
    await expect(moves.first()).toHaveClass(/black/);
    await expect(moves.nth(1)).toHaveClass(/white/);
    await expect(moves.first().locator('san')).toHaveText(/^[A-HJ-T](1?\d)$/);
    await expect(page.locator('.puzzle__moves move.active')).toHaveCount(1);
    await expect(moves.first()).toHaveClass(/active/);

    // the board shows the position after each move: the move's stone is on it
    const points = await page.evaluate(() => {
      const w = window as any;
      return w.puzzle.ctrl.solution.slice(1).map((n: { move: string }) => n.move) as string[];
    });
    const colors = ['X', 'O', 'X'];
    await expect.poll(() => stoneAt(page, points[0])).toBe(colors[0]);
    await moves.nth(2).click();
    await expect(moves.nth(2)).toHaveClass(/active/);
    await expect.poll(() => stoneAt(page, points[2])).toBe(colors[2]);
    // the buttons and the arrow keys move the cursor
    await page.getByRole('button', { name: 'Previous move' }).click();
    await expect(moves.nth(1)).toHaveClass(/active/);
    await key(page, 'left');
    await expect(moves.first()).toHaveClass(/active/);
    await page.getByRole('button', { name: 'First position' }).click();
    await expect(page.locator('.puzzle__moves move.active')).toHaveCount(0);
    await expect.poll(() => stoneAt(page, points[0])).toBe('.');
    await key(page, 'end');
    await expect(moves.last()).toHaveClass(/active/);
    await expect(page.getByRole('button', { name: 'Next move' })).toBeDisabled();
    // the board shows a picture of the position: a click does nothing (White is to move here, so
    // a click that got through would place a white stone, not a black one)
    await play(page, 'ee');
    await expect.poll(() => stoneAt(page, 'ee')).toBe('.');
    expect(opened.completed).toHaveLength(1);
    expect(opened.problems).toEqual({ requests: [], errors: [] });
  });

  test('the solution can be opened after a win too', async ({ page }) => {
    const opened = await openPuzzle(page, { puzzle: straightThree, rating: 1500 });
    await play(page, rightFirst(straightThree));
    await expect(feedback(page)).toHaveClass(/after/);
    await feedback(page).getByRole('button', { name: 'View the solution' }).click();
    await expect(page.locator('.puzzle__moves move')).toHaveCount(1);
    await expect(page.locator('.puzzle__moves move san')).toHaveText('B19');
    // the win stays a win: nothing more is sent
    expect(opened.completed).toEqual([{ theme: 'mix', id: 'strt3', win: true, rated: true }]);
  });

  test('a guest gets puzzles without ratings, votes need an account', async ({ page }) => {
    const opened = await openPuzzle(page, { puzzle: straightThree, next: centreThree });
    await expect(page.locator('.puzzle__side__user')).toContainText('To get personalised puzzles:');
    await play(page, rightFirst(straightThree));
    await expect(feedback(page)).toHaveClass(/after/);
    await expect(page.locator('.puzzle__vote')).toHaveCount(0);
    expect(opened.completed).toHaveLength(1);
    await page.locator('.puzzle__feedback .continue').click();
    await expect(page.locator('.puzzle__side__metas a')).toHaveText('#18Q2Y');
  });

  test('votes and theme votes of a signed-in player', async ({ page }) => {
    const opened = await openPuzzle(page, { puzzle: straightThree, rating: 1500 });
    await play(page, rightFirst(straightThree));
    await page.locator('.puzzle__vote .vote-up').click();
    await expect(page.locator('.puzzle__vote .vote-up')).toHaveClass(/active/);
    expect(opened.votes).toEqual([{ id: 'strt3', vote: true }]);
    // the themes the generator derives from the position (goal, place) can't be voted on; the others can
    await expect(page.locator('.puzzle__themes__lock')).toHaveCount(3);
    await expect(page.locator('.puzzle__themes__selector option')).toHaveText([
      'Add another theme',
      'Capturing race',
      'Eye shape',
      'Ko',
      'Snapback',
      'Tesuji',
      'Throw-in',
    ]);
  });

  test('N goes to the next puzzle once this one is over', async ({ page }) => {
    await openPuzzle(page, { puzzle: straightThree, next: centreThree, rating: 1500 });
    await key(page, 'n');
    await expect(feedback(page)).toHaveClass(/play/);
    await play(page, rightFirst(straightThree));
    await expect(feedback(page)).toHaveClass(/after/);
    await key(page, 'n');
    await expect(page.locator('.puzzle__side__metas a')).toHaveText('#18Q2Y');
  });

  test('the board plays its sounds and the page speaks the result', async ({ page }) => {
    await openPuzzle(page, { puzzle: straightThree, rating: 1500 });
    await play(page, rightFirst(straightThree));
    await expect(feedback(page)).toHaveClass(/after/);
    expect(await sounds(page)).toContain('move');
    expect(await page.evaluate(() => (window as any).spoken)).toEqual(['Success!']);
  });
});

test.describe('phone', () => {
  test.use({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });

  test('Confirm moves: a tap previews the stone, Confirm plays it', async ({ page }) => {
    const opened = await openPuzzle(page, { puzzle: straightThree, rating: 1500 });
    const confirm = page.getByRole('button', { name: 'Confirm move' });
    await expect(confirm).toBeVisible();
    await expect(confirm).toBeDisabled();
    const right = rightFirst(straightThree);
    const wrong = wrongFirst(straightThree);

    // a tap on the wrong point only previews it; another point takes the preview over
    await play(page, wrong, true);
    await expect(confirm).toBeEnabled();
    expect(await line(page)).toEqual([]);
    expect(await stoneAt(page, wrong)).toBe('.');
    await play(page, right, true);
    expect(await line(page)).toEqual([]);
    await expect(confirm).toBeEnabled();
    expect(opened.completed).toEqual([]);

    // the button plays the stone that waits: right, so the puzzle is solved
    await confirm.click();
    await expect(feedback(page)).toHaveClass(/after/);
    expect(await line(page)).toEqual([right]);
    expect(opened.completed).toEqual([{ theme: 'mix', id: 'strt3', win: true, rated: true }]);
    await expect(page.getByRole('button', { name: 'Confirm move' })).toHaveCount(0);
  });

  test('Confirm moves: a second tap on the same point plays it', async ({ page }) => {
    const opened = await openPuzzle(page, { puzzle: straightThree, next: centreThree, rating: 1500 });
    const wrong = wrongFirst(straightThree);
    await play(page, wrong, true);
    expect(await line(page)).toEqual([]);
    await play(page, wrong, true);
    await expect(feedback(page)).toHaveClass(/fail/);
    expect(await line(page)).toEqual([wrong, rightFirst(straightThree)]);
    expect(opened.completed).toEqual([{ theme: 'mix', id: 'strt3', win: false, rated: true }]);
    // after the wrong line there is nothing to confirm
    await expect(page.getByRole('button', { name: 'Confirm move' })).toBeDisabled();
    await feedback(page).getByRole('button', { name: 'Try again' }).click();
    await expect(feedback(page)).toHaveClass(/play/);
    await boardMoves(page, 0);
  });

  test('with Confirm moves off, a tap plays at once', async ({ page }) => {
    await openPuzzle(page, { puzzle: straightThree, rating: 1500, confirmMoves: ConfirmMoves.NEVER });
    await expect(page.getByRole('button', { name: 'Confirm move' })).toHaveCount(0);
    await play(page, rightFirst(straightThree), true);
    await expect(feedback(page)).toHaveClass(/after/);
  });

  test('the layout fits the screen: the board, its source line, the buttons', async ({ page }) => {
    await openPuzzle(page, { puzzle: pyramidFour, rating: 1500 });
    const box = (await page.locator('.puzzle__go-board svg').first().boundingBox())!;
    expect(box.x).toBeGreaterThanOrEqual(0);
    expect(box.x + box.width).toBeLessThanOrEqual(390);
    // no sideways scrolling
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
    // the source line sits under the board; Confirm is a 44 px target
    const source = (await page.locator('.puzzle__source').boundingBox())!;
    expect(source.y).toBeGreaterThanOrEqual(box.y + box.height - 1);
    const button = (await page.getByRole('button', { name: 'Confirm move' }).boundingBox())!;
    expect(button.height).toBeGreaterThanOrEqual(44);
  });
});
