package lila.puzzle

import chess.IntRating
import chess.rating.glicko.Glicko
import reactivemongo.api.bson.{ BSONDocument, BSONDouble, BSONInteger, BSONLong, BSONString }

// LiGo (ADR 0025): a puzzle is a Go problem in OGS goban's puzzle format, not a forced chess line.
// The server only stores it and sends it to the browser, where goban follows `tree` and decides
// whether the player was right. So `tree` and `prov` stay as BSON sub-documents: this class never
// reads inside them, except to render the one-line source (`Puzzle.sourceLine`).
case class Puzzle(
    id: PuzzleId,
    size: Int, // the board is size x size: 9, 13 or 19
    bounds: Option[Puzzle.Bounds], // the part of the board to show, all of it if absent
    setup: Puzzle.Setup,
    color: Color, // the player's colour: who moves first
    tree: BSONDocument, // goban's move_tree, kept as stored
    goal: String, // "live" or "kill" (the classics may also have "ko", "capture", "connect")
    glicko: Glicko,
    plays: Int,
    vote: Float, // denormalized ratio of voteUp/voteDown
    themes: Set[PuzzleTheme.Key],
    prov: Option[BSONDocument] // provenance, see ADR 0024 section 3
):

  def rating: IntRating = glicko.intRating

  def hasTheme(anyOf: PuzzleTheme*) = anyOf.exists(t => themes(t.key))

  /** One line for under the board: where the puzzle comes from. */
  def source: String = Puzzle.sourceLine(prov)

object Puzzle:

  val idSize = 5

  def toId(id: String) = (id.size == idSize).option(PuzzleId(id))

  /** goban's `bounds`: the rows and columns shown, counted from 0 at the top left, both ends included. */
  case class Bounds(top: Int, left: Int, bottom: Int, right: Int)

  /** goban's `initial_state`: the setup stones as SGF points run together, e.g. "aabbcc". */
  case class Setup(black: String, white: String)

  /** An SGF point list ("aabb") as (column, row) pairs counted from 0 at the top left. */
  def sgfPoints(points: String): List[(Int, Int)] =
    points
      .grouped(2)
      .toList
      .collect:
        case s if s.length == 2 && s.forall(c => c >= 'a' && c <= 's') => (s(0) - 'a', s(1) - 'a')

  // a number written by mongosh, lila or Mongo's shell may come as an int, a long or a double
  private[puzzle] def number(doc: BSONDocument, key: String): Option[Long] =
    doc
      .get(key)
      .flatMap:
        case BSONInteger(i) => Some(i.toLong)
        case BSONLong(l) => Some(l)
        case BSONDouble(d) if d.isWhole => Some(d.toLong)
        case _ => None

  private def text(doc: BSONDocument, key: String): Option[String] =
    doc.get(key).collect { case BSONString(s) => s }

  /* The generator's provenance has `source: "generated"` and a `seed`. A transcribed classic has
   * `work`, `edition` and `problem` (tools/puzzles/schema/puzzle.schema.json). */
  def sourceLine(prov: Option[BSONDocument]): String =
    prov
      .flatMap: doc =>
        if text(doc, "source").contains("generated") then
          Some(number(doc, "seed").fold("Generated by LiGo")(seed => s"Generated by LiGo (seed $seed)"))
        else
          text(doc, "work").map: work =>
            val edition = text(doc, "edition").fold("")(e => s" ($e)")
            val problem = text(doc, "problem").fold("")(p => s", problem $p")
            s"$work$edition$problem"
      .getOrElse("Source unknown")

  case class UserResult(
      puzzleId: PuzzleId,
      userId: UserId,
      win: PuzzleWin,
      rating: (IntRating, IntRating)
  )

  object BSONFields:
    val id = "_id"
    val size = "size"
    val bounds = "bounds"
    val setup = "setup"
    val player = "player"
    val tree = "tree"
    val goal = "goal"
    val prov = "prov"
    val glicko = "glicko"
    val vote = "vote"
    val voteUp = "vu"
    val voteDown = "vd"
    val plays = "plays"
    val themes = "themes"
    val day = "day"
    val issue = "issue"
