import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { describe, test } from 'node:test';
import { fileURLToPath } from 'node:url';

import { boardRatio, goalText, resolveConfirm } from '../src/go';
import type { MoveTree, PuzzleJson } from '../src/interfaces';
import { buildSolution, pointName, positionPuzzle, puzzleSgf, solutionPoints } from '../src/solution';

/** The straight three in the corner, Black to live at b1 (libs/board's test puzzle). */
const straightThree: PuzzleJson = {
  id: 'strt3',
  rating: 700,
  plays: 0,
  themes: ['lifeAndDeath'],
  goal: 'live',
  source: 'Generated by LiGo (seed 1)',
  width: 19,
  height: 19,
  bounds: { top: 0, left: 0, bottom: 4, right: 6 },
  initial_state: { black: 'abbbcbdbda', white: 'acbcccdcecebea' },
  initial_player: 'black',
  move_tree: {
    x: -1,
    y: -1,
    branches: [
      { x: 0, y: 0, branches: [{ x: 1, y: 0, wrong_answer: true }] },
      { x: 1, y: 0, correct_answer: true },
    ],
  },
  puzzle_player_move_mode: 'free',
  puzzle_opponent_move_mode: 'automatic',
};

describe('the right line of a tree', () => {
  test('skips a refutation listed first and takes the first line that ends right', () => {
    assert.deepEqual(solutionPoints(straightThree.move_tree), ['ba']);
  });

  test('a line is the player’s moves and the replies in order', () => {
    const tree: MoveTree = {
      x: -1,
      y: -1,
      branches: [
        {
          x: 3,
          y: 3,
          branches: [
            { x: 4, y: 4, branches: [{ x: 5, y: 5, correct_answer: true }] },
            { x: 6, y: 6, branches: [{ x: 7, y: 7, wrong_answer: true }] },
          ],
        },
      ],
    };
    assert.deepEqual(solutionPoints(tree), ['dd', 'ee', 'ff']);
  });

  test('a branch that ends without a verdict is not a right line', () => {
    const tree: MoveTree = {
      x: -1,
      y: -1,
      branches: [
        { x: 3, y: 3 },
        { x: 4, y: 4, correct_answer: true },
      ],
    };
    assert.deepEqual(solutionPoints(tree), ['ee']);
  });

  test('a tree with no right line has no solution', () => {
    const tree: MoveTree = { x: -1, y: -1, branches: [{ x: 3, y: 3, wrong_answer: true }] };
    assert.equal(solutionPoints(tree), undefined);
    assert.equal(solutionPoints({ x: -1, y: -1 }), undefined);
  });
});

describe('the solution as Go nodes', () => {
  test('the setup is an SGF root with both colours and the player to move', () => {
    assert.equal(
      puzzleSgf(straightThree),
      '(;GM[1]FF[4]CA[UTF-8]SZ[19]RU[Japanese]KM[0]AB[ab][bb][cb][db][da]AW[ac][bc][cc][dc][ec][eb][ea]PL[B])',
    );
    assert.match(puzzleSgf({ ...straightThree, initial_player: 'white' }), /PL\[W\]\)$/);
  });

  test('every node holds the position after its move, and the root the setup', () => {
    const line = buildSolution(straightThree)!;
    assert.equal(line.length, 2);
    assert.deepEqual(line[0].stones.black.sort(), ['ab', 'bb', 'cb', 'da', 'db'].sort());
    assert.equal(line[1].move, 'ba');
    assert.equal(line[1].color, 'black');
    assert.ok(line[1].stones.black.includes('ba'));
    assert.equal(line[1].toMove, 'white');
  });

  test('every puzzle of the committed set has a solution the rules accept', () => {
    const dir = join(dirname(fileURLToPath(import.meta.url)), '../../../../tools/puzzles/data');
    let checked = 0;
    for (const file of readdirSync(dir).filter(f => /^generated-.*\.json$/.test(f)))
      for (const p of JSON.parse(readFileSync(join(dir, file), 'utf8')) as PuzzleJson[]) {
        const points = solutionPoints(p.move_tree);
        const line = buildSolution(p);
        assert.ok(points?.length, `${p.id} has a right line`);
        assert.equal(line?.length, points.length + 1, `${p.id}: every move of the line is legal`);
        checked++;
      }
    assert.ok(checked >= 200, `checked ${checked} puzzles`);
  });

  test('a position of the solution is a puzzle without a tree, in the position’s colours', () => {
    const line = buildSolution(straightThree)!;
    const shown = positionPuzzle(straightThree, line[1]);
    assert.deepEqual(shown.move_tree, { x: -1, y: -1 });
    assert.equal(shown.initial_player, 'white');
    assert.ok(shown.initial_state.black.includes('ba'));
    assert.equal(shown.bounds, straightThree.bounds);
    assert.ok(straightThree.move_tree.branches, 'the puzzle itself is not changed');
  });

  test('names points as a Go board prints them', () => {
    assert.equal(pointName(19, 'aa'), 'A19');
    assert.equal(pointName(19, 'ss'), 'T1');
    assert.equal(pointName(9, 'ee'), 'E5');
    assert.equal(pointName(19, 'is'), 'J1');
  });
});

describe('the page’s small facts', () => {
  test('Confirm moves: Always always, Touch on a touch screen, Never never, Touch if the pref is missing', () => {
    assert.equal(resolveConfirm(2, false), true);
    assert.equal(resolveConfirm(1, true), true);
    assert.equal(resolveConfirm(1, false), false);
    assert.equal(resolveConfirm(0, true), false);
    assert.equal(resolveConfirm(undefined, true), true);
    assert.equal(resolveConfirm(undefined, false), false);
  });

  test('the goal says what the player does', () => {
    assert.equal(goalText('live', 'black'), 'Black to live');
    assert.equal(goalText('kill', 'white'), 'White to kill');
    assert.equal(goalText('ko', 'white'), 'White to win the ko');
    assert.equal(goalText('something new', 'black'), 'Black to play');
  });

  test('the board’s box is as tall as what the puzzle shows, coordinate bands included', () => {
    // 7 columns and 5 rows of the top left corner: a band on the top and on the left only (to three decimals)
    assert.equal(boardRatio(straightThree, true), 6 / 8);
    assert.equal(boardRatio(straightThree, false), 0.714);
    // the whole board: a band on each side
    assert.equal(boardRatio({ width: 19, bounds: undefined }, true), 1);
    // a region in the middle has no bands
    assert.equal(boardRatio({ width: 19, bounds: { top: 4, left: 6, bottom: 10, right: 14 } }, true), 0.778);
  });
});
